---
triple:          'x86_64-apple-darwin'
binary-path:     app
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _register_user, symObjAddr: 0x0, symBinAddr: 0x100003AB0, symSize: 0xB0 }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _user_count, symObjAddr: 0xF94, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x69, offset: 0x69, size: 0x8, addend: 0x0, symName: _users, symBinAddr: 0x100008010, symSize: 0x0 }
  - { offsetInCU: 0xB2, offset: 0xB2, size: 0x8, addend: 0x0, symName: _register_user, symObjAddr: 0x0, symBinAddr: 0x100003AB0, symSize: 0xB0 }
  - { offsetInCU: 0xC7, offset: 0xC7, size: 0x8, addend: 0x0, symName: _login, symObjAddr: 0xB0, symBinAddr: 0x100003B60, symSize: 0x120 }
  - { offsetInCU: 0x127, offset: 0x127, size: 0x8, addend: 0x0, symName: _print_users, symObjAddr: 0x1D0, symBinAddr: 0x100003C80, symSize: 0x80 }
  - { offsetInCU: 0x159, offset: 0x159, size: 0x8, addend: 0x0, symName: _vulnerable_function, symObjAddr: 0x250, symBinAddr: 0x100003D00, symSize: 0x40 }
  - { offsetInCU: 0x17D, offset: 0x17D, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x290, symBinAddr: 0x100003D40, symSize: 0xFC }
...
